{% set version = "1.3.4" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-smvar
  version: {{ version|replace("-", "_") }}

source:
  fn: SMVar_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/SMVar_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/SMVar/SMVar_{{ version }}.tar.gz

  sha256: aaea3ef7da6cee1bb86fef166df766229c8b7cac9fcf5bc28da7adff5e2c01d6

build:
  noarch: generic
  number: 0

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('SMVar')"  # [not win]
    - "\"%R%\" -e \"library('SMVar')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=SMVar
  license: GPL
  summary: Implements the structural model for variances in order to detect differentially expressed genes from gene expression data
  license_family: GPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
