appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: I4468ZyAPeyZgX9VdZLy9u9tCAOh/OPxZTVI/O0HxcyIXs06h4q3V+J15tDsbKrHpIUZB1HNmoKGblzPSVpeKL0K3VaMytuExNRlN9OeNcL7b4QHJrWo9814HWt/MdTrYcfVhu59/Mw95OBwJ1G4vJpxNq1yDOhjjGDLNysba6wBbZr9xjuVOTF4rdy7U7ojL8Qb7rPA11egUF7OsMrfVbjshrVGT2NYww20uPqmiuJXgOUJpgW+ajJ9sBBqMknxIdovApkFvoU57tNN6xy/MBxEGbnLGlQpArAJqEF04t91/FDflwTbOdVtO7DcimdttmwHKzEVfv1ooXRBWsGmDmT/16kuSMNz3fwAUzNqQwq2ArGF3wxFo6VsKzt9D8rnh4Bek+3PTyB0Y9CR6AJe8kaiASbNbDKheeM3ALdyrw4yCozys7vXBB2AIVVH1z6cVoVkkV7zF8edXW7a8/yQKX5XTxFkGhMlCFIvuVkpNRIS0StHFN4KmlflfQuzKOnfy+2h3Zdwq/Xuou3DGlPj8bcJumhwohfBv3ATial0B0u43ArDGsk98I9n/6toWuI86+cPXzxfP9elmI60G9yQnEHTmcu7TyfDqpace0kLsd61xVI5jJ808TZTugXcfUj01uBbJU48J+be8e8McMwaxUMyOhW4OoIwZc7xV1xNrXM=
conda_forge_output_validation: false
