travis:
  secure:
    BINSTAR_TOKEN: WBUbVzJIGHJCDnDgxAcFF5+M6xhWTVsynBKWD5goQD72GIM+YyWCYSu3h+QrEJzk8hAWUhvoJk2pTT9YJmOy5FJQnM0IgwY4oKLC3jTYCeUveZwbhSOMbTuJnj1zACLDZ/4ohORdQBf7HxZCr/SULP44T5LmORBD6HbekPiGpBRDYVog9/muiZQ3I7/upbEJJ1iZ+j2G3Rjuq+OPuqSFSssPQwU7q5MJ7Bc9Rr/2rjsYx4uxqabjzXyW85NifBskueAIS+t0U9q9Y9gT1g2ze9pIg49GPe6rdIoi/skO+iomFPjE0+2lBt/jKLv2hi/HAk6DUmpTKBEkEX8SqlLjHvhnHsnJJnNlb3AL/IuDqn90sh0gpnMPzabxrtbi5wWHph8zEEiQJdZFb6QqA6mplftXP6hCMTkT3MxadQmgeX2tDvnFDXhBxoQVzUGtvvKbr1ut6ETucd5B86qUN7e3be7yd70reyW8F+Aw4yuEeYoMNpdlnLmvNW/KicTE5cwHuEZlLB+Gva2a41hraoscr9dOollv2QkGSkOYXU5ajZqjhcxZMBLFTdJOFHbXrwOWU32c5iy79QPS2r4P3ltqzfcd6iHdsFveK+UtCIR+Kd1F1h1ZtEyclD1wMAnTbtNOHvVeQczX06rDu3Qx3/aLEUzFTWlCmmTDkqR0TbwVC2o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
